import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../components/Header";
import { getSession } from "next-auth/react";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
import { db } from "../../firebase";
import { collection, getDocs } from "firebase/firestore";
import { useCollection } from "react-firebase-hooks/firestore";
import { doc, getDoc } from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
	if (!props.session) return <Login />;
	return (
		<>
			<Head>
				<title>Facebook</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="flex">
				<Sidebar />
				<Feed posts={props.posts} />
				<Widgets />
			</main>
		</>
	);
}

export async function getServerSideProps(context: any) {
	const session: any = await getSession(context);
	// const posts = await getDocs(collection(db, "posts"));
	const querySnapshot = await getDocs(collection(db, "posts"));
	const docs = querySnapshot.docs.map((doc) => ({
		// doc.data() is never undefined for query doc snapshots
		id: doc.id,
		...doc.data(),
	}));

	// const docs = posts?.forEach((doc) => ({
	// 	id: doc.id,
	// 	...doc.data(),
	// }));
	return {
		props: {
			session,
			posts: docs,
		},
	};
}
